# Generated by Django 5.0 on 2025-10-06 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_ordemdecompra_itemordemdecompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='tempo_entrega_dias',
            field=models.PositiveIntegerField(default=7, help_text='Tempo médio de entrega do fornecedor em dias. Essencial para o cálculo de reposição.'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0, help_text='Estoque de segurança.'),
        ),
    ]
