# Generated by Django 5.0 on 2025-10-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_popular_dados_iniciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras (EAN-13, etc.) da variação.', max_length=100, null=True, unique=True),
        ),
    ]
