# Generated by Django 5.0 on 2025-10-17 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_cliente_movimentacaoestoque_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_meta', models.DecimalField(decimal_places=2, help_text='O valor da meta de faturamento para o mês.', max_digits=12)),
                ('mes', models.PositiveIntegerField(help_text='O mês da meta (1 para Janeiro, 12 para Dezembro).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ano', models.PositiveIntegerField(help_text='O ano da meta.')),
            ],
            options={
                'verbose_name': 'Meta de Venda',
                'verbose_name_plural': 'Metas de Vendas',
                'unique_together': {('mes', 'ano')},
            },
        ),
    ]
